### ISSUE TITLE
Manage Drawing

### ISSUE THREAD

**Issue by fuad0019** [sweat-tek/JHotDrawGrp6#7]

**Comment by Skashe** [comment]
As a user, I want to be able to create a new drawing, open a new window (with a potential existing or with a new drawing), Close the drawing and exit the program.

**Comment by Skashe** [comment]
**THIS ISSUE HAS BEEN CLOSED IN FAVOR OF A BETTER OPTION. DISREGARD ANY WORK DONE ON THIS.**
